DROP TABLE nc_vreg_history;

CREATE TABLE nc_vreg_history (
    data_date DATE,
    county_id TEXT,
    county_desc TEXT,
    voter_reg_num TEXT,
    ncid TEXT,
    last_name TEXT,
    first_name TEXT,
    middle_name TEXT,
    name_suffix_lbl TEXT,
    status_cd TEXT,
    voter_status_desc TEXT,
    reason_cd TEXT,
    voter_status_reason_desc TEXT,
    res_street_address TEXT,
    res_city_desc TEXT,
    state_cd TEXT,
    zip_code TEXT,
    mail_addr1 TEXT,
    mail_addr2 TEXT,
    mail_addr3 TEXT,
    mail_addr4 TEXT,
    mail_city TEXT,
    mail_state TEXT,
    mail_zipcode TEXT,
    full_phone_number TEXT,
    confidential_ind TEXT,
	-- I'm keeping registr_dt as TEXT instead of casting to DATE
	-- The state's source file occasionally contains literal "##/##/####" strings in place of a real date
	-- This breaks a DATE cast when I import data
	-- I have not confirmed the reason/cause, may revisit later
	-- See 'nc_vreg_registr_dt_research.sql' for initial research
	registr_dt TEXT,
    registr_dt TEXT,
    race_code TEXT,
    ethnic_code TEXT,
    party_cd TEXT,
    gender_code TEXT,
    birth_year INTEGER,
    age_at_year_end INTEGER,
    birth_state TEXT,
    drivers_lic TEXT,
    precinct_abbrv TEXT,
    precinct_desc TEXT,
    municipality_abbrv TEXT,
    municipality_desc TEXT,
    ward_abbrv TEXT,
    ward_desc TEXT,
    cong_dist_abbrv TEXT,
    super_court_abbrv TEXT,
    judic_dist_abbrv TEXT,
    nc_senate_abbrv TEXT,
    nc_house_abbrv TEXT,
    county_commiss_abbrv TEXT,
    county_commiss_desc TEXT,
    township_abbrv TEXT,
    township_desc TEXT,
    school_dist_abbrv TEXT,
    school_dist_desc TEXT,
    fire_dist_abbrv TEXT,
    fire_dist_desc TEXT,
    water_dist_abbrv TEXT,
    water_dist_desc TEXT,
    sewer_dist_abbrv TEXT,
    sewer_dist_desc TEXT,
    sanit_dist_abbrv TEXT,
    sanit_dist_desc TEXT,
    rescue_dist_abbrv TEXT,
    rescue_dist_desc TEXT,
    munic_dist_abbrv TEXT,
    munic_dist_desc TEXT,
    dist_1_abbrv TEXT,
    dist_1_desc TEXT,
    vtd_abbrv TEXT,
    vtd_desc TEXT,
    PRIMARY KEY (ncid, data_date)
);

/*
COPY nc_vreg_history FROM ''
WITH (FORMAT csv, DELIMITER ',', QUOTE '"', ESCAPE '"', HEADER true, ENCODING 'UTF8');
*/